#lang racket

(require json "graph.rkt")
(provide toy-graph example-graph ten twenty-tree forty-tree eighty-tree)

(define vertices (list '1 '2 '3))
(define edges '((1 . 2)))
(define toy-graph (make-graph vertices edges))

; A simple graph (tree) with 6 nodes and 5 edges
(define example-graph
  "{\"nodes\": [{\"name\": \"a\", \"index\": 0}, {\"name\": \"b\", \"index\": 1}, {\"name\": \"c\", \"index\": 2}, 
                {\"name\": \"d\", \"index\": 3}, {\"name\": \"e\", \"index\": 4}, {\"name\": \"f\", \"index\": 5}],
    \"links\": [
      {\"source\": 0, \"target\": 1},
      {\"source\": 0, \"target\": 2},
      {\"source\": 1, \"target\": 3},
      {\"source\": 2, \"target\": 4},
      {\"source\": 2, \"target\": 5}]}")

(define example-graph2
  "{\"nodes\": [{\"name\": \"a\", \"index\": 0}, {\"name\": \"b\", \"index\": 1}, {\"name\": \"c\", \"index\": 2}],
    \"links\": [
      {\"source\": 0, \"target\": 1},
      {\"source\": 1, \"target\": 2}]}")

(define ten "{\"nodes\":[{\"id\":0},{\"id\":1},{\"id\":2},{\"id\":3},{\"id\":4},{\"id\":5},{\"id\":6},{\"id\":7},{\"id\":8},{\"id\":9}],\"links\":[{\"source\":0,\"target\":1},{\"source\":1,\"target\":2},{\"source\":0,\"target\":3},{\"source\":0,\"target\":4},{\"source\":2,\"target\":5},{\"source\":3,\"target\":6},{\"source\":5,\"target\":7},{\"source\":3,\"target\":8},{\"source\":2,\"target\":9}]}")

(define twenty-tree "{
  \"nodes\": [
    {\"id\": 0},
    {\"id\": 1},
    {\"id\": 2},
    {\"id\": 3},
    {\"id\": 4},
    {\"id\": 5},
    {\"id\": 6},
    {\"id\": 7},
    {\"id\": 8},
    {\"id\": 9},
    {\"id\": 10},
    {\"id\": 11},
    {\"id\": 12},
    {\"id\": 13},
    {\"id\": 14},
    {\"id\": 15},
    {\"id\": 16},
    {\"id\": 17},
    {\"id\": 18},
    {\"id\": 19}
  ],
  \"links\": [
    {\"source\": 0,\"target\": 1},
    {\"source\": 1,\"target\": 2},
    {\"source\": 2,\"target\": 3},
    {\"source\": 0,\"target\": 4},
    {\"source\": 4,\"target\": 5},
    {\"source\": 0,\"target\": 6},
    {\"source\": 6,\"target\": 7},
    {\"source\": 1,\"target\": 8},
    {\"source\": 6,\"target\": 9},
    {\"source\": 9,\"target\": 10},
    {\"source\": 9,\"target\": 11},
    {\"source\": 9,\"target\": 12},
    {\"source\": 4,\"target\": 13},
    {\"source\": 2,\"target\": 14},
    {\"source\": 3,\"target\": 15},
    {\"source\": 1,\"target\": 16},
    {\"source\": 11,\"target\": 17},
    {\"source\": 8,\"target\": 18},
    {\"source\": 5,\"target\": 19}
  ]
}")

(define twenty-tree2 "{
  \"nodes\": [
    {\"name\": \"Toprato\"},
    {\"name\": \"Fella\"},
    {\"name\": \"Tirti\"},
    {\"name\": \"LA Piu' Bella\"},
    {\"name\": \"Deep Shadow 1-5-8\"},
    {\"name\": \"Oobiscus\"},
    {\"name\": \"Rioky\"},
    {\"name\": \"Klashe\"},
    {\"name\": \"Tau Beta\"},
    {\"name\": \"311040\"},
    {\"name\": \"Nevf Zotsamm\"},
    {\"name\": \"Gnaron\"},
    {\"name\": \"Green Dor\"},
    {\"name\": \"Gravity\"},
    {\"name\": \"Jurrawensaed\"},
    {\"name\": \"Andrill Primus\"},
    {\"name\": \"Ulti-Mad\"},
    {\"name\": \"Jellyfish\"},
    {\"name\": \"Yersa\"},
    {\"name\": \"Therfady\"}
  ],
  \"links\": [
    {\"target\": 1,\"source\": 0,\"value\": 1},
    {\"target\": 2,\"source\": 0,\"value\": 1},
    {\"target\": 9,\"source\": 0,\"value\": 1},
    {\"target\": 11,\"source\": 0,\"value\": 1},
    {\"target\": 3,\"source\": 2,\"value\": 1},
    {\"target\": 4,\"source\": 3,\"value\": 1},
    {\"target\": 5,\"source\": 4,\"value\": 1},
    {\"target\": 6,\"source\": 5,\"value\": 1},
    {\"target\": 10,\"source\": 6,\"value\": 1},
    {\"target\": 8,\"source\": 7,\"value\": 1},
    {\"target\": 11,\"source\": 7,\"value\": 1},
    {\"target\": 12,\"source\": 8,\"value\": 1},
    {\"target\": 18,\"source\": 9,\"value\": 1},
    {\"target\": 13,\"source\": 12,\"value\": 1},
    {\"target\": 14,\"source\": 12,\"value\": 1},
    {\"target\": 15,\"source\": 12,\"value\": 1},
    {\"target\": 16,\"source\": 12,\"value\": 1},
    {\"target\": 17,\"source\": 12,\"value\": 1},
    {\"target\": 19,\"source\": 12,\"value\": 1}
  ]
}")

(define forty-tree "{
  \"nodes\": [
    {\"name\": \"Toprato\"},
    {\"name\": \"Fella\"},
    {\"name\": \"Tirti\"},
    {\"name\": \"LA Piu' Bella\"},
    {\"name\": \"Deep Shadow 1-5-8\"},
    {\"name\": \"Oobiscus\"},
    {\"name\": \"Rioky\"},
    {\"name\": \"Klashe\"},
    {\"name\": \"Tau Beta\"},
    {\"name\": \"311040\"},
    {\"name\": \"Nevf Zotsamm\"},
    {\"name\": \"Gnaron\"},
    {\"name\": \"Green Dor\"},
    {\"name\": \"Gravity\"},
    {\"name\": \"Jurrawensaed\"},
    {\"name\": \"Andrill Primus\"},
    {\"name\": \"Ulti-Mad\"},
    {\"name\": \"Jellyfish\"},
    {\"name\": \"Yersa\"},
    {\"name\": \"Therfady\"},
    {\"name\": \"SC 09\"},
    {\"name\": \"Glueck\"},
    {\"name\": \"Fiddle\"},
    {\"name\": \"LV-017\"},
    {\"name\": \"Sardinle\"},
    {\"name\": \"Latalava\"},
    {\"name\": \"Penumbra\"},
    {\"name\": \"Chi Qoppa\"},
    {\"name\": \"Vopru Maufyb\"},
    {\"name\": \"Onadha\"},
    {\"name\": \"Muplita Furr\"},
    {\"name\": \"Psi Epsilon\"},
    {\"name\": \"Dimloon\"},
    {\"name\": \"Tanned I\"},
    {\"name\": \"Woolaris 10\"},
    {\"name\": \"Semend\"},
    {\"name\": \"Blacus\"},
    {\"name\": \"Darknok\"},
    {\"name\": \"Oastar Secundus\"},
    {\"name\": \"Green One\"}
  ],
  \"links\": [
    {\"target\": 1,\"source\": 0,\"value\": 1},
    {\"target\": 2,\"source\": 0,\"value\": 1},
    {\"target\": 9,\"source\": 0,\"value\": 1},
    {\"target\": 11,\"source\": 0,\"value\": 1},
    {\"target\": 3,\"source\": 2,\"value\": 1},
    {\"target\": 4,\"source\": 3,\"value\": 1},
    {\"target\": 5,\"source\": 4,\"value\": 1},
    {\"target\": 6,\"source\": 5,\"value\": 1},
    {\"target\": 10,\"source\": 6,\"value\": 1},
    {\"target\": 8,\"source\": 7,\"value\": 1},
    {\"target\": 11,\"source\": 7,\"value\": 1},
    {\"target\": 12,\"source\": 8,\"value\": 1},
    {\"target\": 18,\"source\": 9,\"value\": 1},
    {\"target\": 35,\"source\": 10,\"value\": 1},
    {\"target\": 13,\"source\": 12,\"value\": 1},
    {\"target\": 14,\"source\": 12,\"value\": 1},
    {\"target\": 15,\"source\": 12,\"value\": 1},
    {\"target\": 16,\"source\": 12,\"value\": 1},
    {\"target\": 17,\"source\": 12,\"value\": 1},
    {\"target\": 19,\"source\": 12,\"value\": 1},
    {\"target\": 20,\"source\": 12,\"value\": 1},
    {\"target\": 21,\"source\": 12,\"value\": 1},
    {\"target\": 23,\"source\": 12,\"value\": 1},
    {\"target\": 25,\"source\": 12,\"value\": 1},
    {\"target\": 26,\"source\": 12,\"value\": 1},
    {\"target\": 28,\"source\": 12,\"value\": 1},
    {\"target\": 29,\"source\": 12,\"value\": 1},
    {\"target\": 31,\"source\": 12,\"value\": 1},
    {\"target\": 24,\"source\": 13,\"value\": 1},
    {\"target\": 22,\"source\": 15,\"value\": 1},
    {\"target\": 30,\"source\": 18,\"value\": 1},
    {\"target\": 39,\"source\": 19,\"value\": 1},
    {\"target\": 27,\"source\": 22,\"value\": 1},
    {\"target\": 32,\"source\": 31,\"value\": 1},
    {\"target\": 33,\"source\": 31,\"value\": 1},
    {\"target\": 34,\"source\": 31,\"value\": 1},
    {\"target\": 36,\"source\": 31,\"value\": 1},
    {\"target\": 37,\"source\": 31,\"value\": 1},
    {\"target\": 38,\"source\": 31,\"value\": 1}
  ]
}")

(define eighty-tree "{
  \"nodes\": [
    {\"name\": \"Toprato\"},
    {\"name\": \"Fella\"},
    {\"name\": \"Tirti\"},
    {\"name\": \"LA Piu' Bella\"},
    {\"name\": \"Deep Shadow 1-5-8\"},
    {\"name\": \"Oobiscus\"},
    {\"name\": \"Rioky\"},
    {\"name\": \"Klashe\"},
    {\"name\": \"Tau Beta\"},
    {\"name\": \"311040\"},
    {\"name\": \"Nevf Zotsamm\"},
    {\"name\": \"Gnaron\"},
    {\"name\": \"Green Dor\"},
    {\"name\": \"Gravity\"},
    {\"name\": \"Jurrawensaed\"},
    {\"name\": \"Andrill Primus\"},
    {\"name\": \"Ulti-Mad\"},
    {\"name\": \"Jellyfish\"},
    {\"name\": \"Yersa\"},
    {\"name\": \"Therfady\"},
    {\"name\": \"SC 09\"},
    {\"name\": \"Glueck\"},
    {\"name\": \"Fiddle\"},
    {\"name\": \"LV-017\"},
    {\"name\": \"Sardinle\"},
    {\"name\": \"Latalava\"},
    {\"name\": \"Penumbra\"},
    {\"name\": \"Chi Qoppa\"},
    {\"name\": \"Vopru Maufyb\"},
    {\"name\": \"Onadha\"},
    {\"name\": \"Muplita Furr\"},
    {\"name\": \"Psi Epsilon\"},
    {\"name\": \"Dimloon\"},
    {\"name\": \"Tanned I\"},
    {\"name\": \"Woolaris 10\"},
    {\"name\": \"Semend\"},
    {\"name\": \"Blacus\"},
    {\"name\": \"Darknok\"},
    {\"name\": \"Oastar Secundus\"},
    {\"name\": \"Green One\"},
    {\"name\": \"Kayin Minor A\"},
    {\"name\": \"Arton\"},
    {\"name\": \"Anerstis\"},
    {\"name\": \"Lament\"},
    {\"name\": \"Shaison\"},
    {\"name\": \"Rekini-H-S6\"},
    {\"name\": \"Darkless\"},
    {\"name\": \"MBTP 20\"},
    {\"name\": \"Yankee Quebec\"},
    {\"name\": \"Shere Jauj-Bred\"},
    {\"name\": \"Embalm\"},
    {\"name\": \"Small Rock 4\"},
    {\"name\": \"Libra-D-S3\"},
    {\"name\": \"Dying Warmth\"},
    {\"name\": \"Sofa\"},
    {\"name\": \"Grobnor\"},
    {\"name\": \"Forbidden 1\"},
    {\"name\": \"Glimmer II\"},
    {\"name\": \"Aleksis\"},
    {\"name\": \"Relu\"},
    {\"name\": \"Scoff\"},
    {\"name\": \"Elas\"},
    {\"name\": \"Great Crater\"},
    {\"name\": \"Leuprekota\"},
    {\"name\": \"Yetton\"},
    {\"name\": \"Fheyhs\"},
    {\"name\": \"Edriwoise\"},
    {\"name\": \"Usque\"},
    {\"name\": \"Surfatu\"},
    {\"name\": \"Drumana\"},
    {\"name\": \"Hausner\"},
    {\"name\": \"Vitalis\"},
    {\"name\": \"Hyacinta IV\"},
    {\"name\": \"Revenge of the Lith\"},
    {\"name\": \"Asclephyrus\"},
    {\"name\": \"Little Friend VI\"},
    {\"name\": \"Fontelitio\"},
    {\"name\": \"Shinmien\"},
    {\"name\": \"Nine\"},
    {\"name\": \"Kalgash\"}
  ],
  \"links\": [
    {\"target\": 1,\"source\": 0,\"value\": 1},
    {\"target\": 2,\"source\": 0,\"value\": 1},
    {\"target\": 9,\"source\": 0,\"value\": 1},
    {\"target\": 11,\"source\": 0,\"value\": 1},
    {\"target\": 78,\"source\": 1,\"value\": 1},
    {\"target\": 3,\"source\": 2,\"value\": 1},
    {\"target\": 4,\"source\": 3,\"value\": 1},
    {\"target\": 5,\"source\": 4,\"value\": 1},
    {\"target\": 6,\"source\": 5,\"value\": 1},
    {\"target\": 10,\"source\": 6,\"value\": 1},
    {\"target\": 8,\"source\": 7,\"value\": 1},
    {\"target\": 11,\"source\": 7,\"value\": 1},
    {\"target\": 12,\"source\": 8,\"value\": 1},
    {\"target\": 18,\"source\": 9,\"value\": 1},
    {\"target\": 35,\"source\": 10,\"value\": 1},
    {\"target\": 13,\"source\": 12,\"value\": 1},
    {\"target\": 14,\"source\": 12,\"value\": 1},
    {\"target\": 15,\"source\": 12,\"value\": 1},
    {\"target\": 16,\"source\": 12,\"value\": 1},
    {\"target\": 17,\"source\": 12,\"value\": 1},
    {\"target\": 19,\"source\": 12,\"value\": 1},
    {\"target\": 20,\"source\": 12,\"value\": 1},
    {\"target\": 21,\"source\": 12,\"value\": 1},
    {\"target\": 23,\"source\": 12,\"value\": 1},
    {\"target\": 25,\"source\": 12,\"value\": 1},
    {\"target\": 26,\"source\": 12,\"value\": 1},
    {\"target\": 28,\"source\": 12,\"value\": 1},
    {\"target\": 29,\"source\": 12,\"value\": 1},
    {\"target\": 31,\"source\": 12,\"value\": 1},
    {\"target\": 24,\"source\": 13,\"value\": 1},
    {\"target\": 45,\"source\": 14,\"value\": 1},
    {\"target\": 22,\"source\": 15,\"value\": 1},
    {\"target\": 49,\"source\": 16,\"value\": 1},
    {\"target\": 30,\"source\": 18,\"value\": 1},
    {\"target\": 39,\"source\": 19,\"value\": 1},
    {\"target\": 40,\"source\": 20,\"value\": 1},
    {\"target\": 50,\"source\": 21,\"value\": 1},
    {\"target\": 27,\"source\": 22,\"value\": 1},
    {\"target\": 63,\"source\": 23,\"value\": 1},
    {\"target\": 72,\"source\": 24,\"value\": 1},
    {\"target\": 60,\"source\": 26,\"value\": 1},
    {\"target\": 68,\"source\": 27,\"value\": 1},
    {\"target\": 59,\"source\": 29,\"value\": 1},
    {\"target\": 32,\"source\": 31,\"value\": 1},
    {\"target\": 33,\"source\": 31,\"value\": 1},
    {\"target\": 34,\"source\": 31,\"value\": 1},
    {\"target\": 36,\"source\": 31,\"value\": 1},
    {\"target\": 37,\"source\": 31,\"value\": 1},
    {\"target\": 38,\"source\": 31,\"value\": 1},
    {\"target\": 58,\"source\": 32,\"value\": 1},
    {\"target\": 75,\"source\": 33,\"value\": 1},
    {\"target\": 41,\"source\": 34,\"value\": 1},
    {\"target\": 48,\"source\": 35,\"value\": 1},
    {\"target\": 76,\"source\": 36,\"value\": 1},
    {\"target\": 42,\"source\": 37,\"value\": 1},
    {\"target\": 44,\"source\": 38,\"value\": 1},
    {\"target\": 46,\"source\": 38,\"value\": 1},
    {\"target\": 47,\"source\": 38,\"value\": 1},
    {\"target\": 43,\"source\": 39,\"value\": 1},
    {\"target\": 57,\"source\": 40,\"value\": 1},
    {\"target\": 67,\"source\": 41,\"value\": 1},
    {\"target\": 74,\"source\": 42,\"value\": 1},
    {\"target\": 51,\"source\": 43,\"value\": 1},
    {\"target\": 52,\"source\": 48,\"value\": 1},
    {\"target\": 53,\"source\": 48,\"value\": 1},
    {\"target\": 54,\"source\": 48,\"value\": 1},
    {\"target\": 55,\"source\": 48,\"value\": 1},
    {\"target\": 56,\"source\": 48,\"value\": 1},
    {\"target\": 61,\"source\": 48,\"value\": 1},
    {\"target\": 62,\"source\": 48,\"value\": 1},
    {\"target\": 64,\"source\": 62,\"value\": 1},
    {\"target\": 65,\"source\": 62,\"value\": 1},
    {\"target\": 66,\"source\": 62,\"value\": 1},
    {\"target\": 69,\"source\": 62,\"value\": 1},
    {\"target\": 70,\"source\": 69,\"value\": 1},
    {\"target\": 71,\"source\": 69,\"value\": 1},
    {\"target\": 73,\"source\": 69,\"value\": 1},
    {\"target\": 77,\"source\": 69,\"value\": 1},
    {\"target\": 79,\"source\": 78,\"value\": 1}
  ]
}")